question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text": "The Python programming language was named after a snake.", "answer": "False"},
    {"text": "There are 8 planets in the solar system.", "answer": "True"},
    {"text": "HTML stands for Hypertext Markup Language.", "answer": "True"},
    {"text": "JavaScript is the same as Java.", "answer": "False"},
    {"text": "The boiling point of water is 100 degrees Celsius.", "answer": "True"},
    {"text": "Mount Everest is the tallest mountain in the world.", "answer": "True"},
    {"text": "A compiler translates the entire code before execution.", "answer": "True"},
    {"text": "An algorithm is a step-by-step procedure to solve a problem.", "answer": "True"},
    {"text": "In most programming languages, array indexes start from 1.", "answer": "False"},
    {"text": "Time complexity of binary search is O(n).", "answer": "False"},
    {"text": "A function that calls itself is known as recursion.", "answer": "True"},
    {"text": "Stacks follow First-In-First-Out (FIFO) principle.", "answer": "False"},
    {"text": "A linked list can only be traversed in one direction.", "answer": "False"},
    {"text": "Merge Sort has a better worst-case time complexity than Bubble Sort.", "answer": "True"},
    {"text": "In a binary tree, each node can have at most two children.", "answer": "True"},
    {"text": "HTTP is a programming language.", "answer": "False"}
]

